version: "3.8"

services:
  hethong-chothuevesi:
    image: openjdk:17-oraclelinux8  # Sử dụng OpenJDK 22
    container_name: hethong-chothuevesi
    ports:
      - "8080:8080"  # Ánh xạ cổng 8080
    networks:
      - hethong-chothuevesi-network
    restart: on-failure
    volumes:
      - ./src:/app  # Mount thư mục mã nguồn vào container
      - ./target:/app/target  # Mount thư mục target chứa file JAR
    working_dir: /app  # Đặt thư mục làm việc
    command: [ "java", "-jar", "/app/target/HETHONGCHOTHUEVESI-0.0.1-SNAPSHOT.jar" ]  # Lệnh chạy ứng dụng Spring Boot từ file JAR

networks:
  hethong-chothuevesi-network:
    driver: bridge

volumes:
  my_mysql_data:
