version: "3.8"

services:
  hethong-chothuevesi:
    image: openjdk:22-oraclelinux8  # Sử dụng OpenJDK 22
    container_name: hethong-chothuevesi
    ports:
      - "8080:8080"  # Ánh xạ cổng 8080
    networks:
      - hethong-chothuevesi-network
    restart: on-failure
    volumes:
      - ./src:/app  # Mount thư mục mã nguồn vào container
      - ./target:/app/target  # Mount thư mục target chứa file JAR
    command: [ "java", "-jar", "/app/target/*.jar" ]  # Lệnh chạy ứng dụng Spring Boot từ file JAR

  hethong-chothuevesi-db:
    image: mysql:oraclelinux9
    container_name: hethong-chothuevesi-db
    ports:
      - "3306:3306"  # Port mặc định của MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mật khẩu cho root user
      MYSQL_DATABASE: HETHONGCHOTHUEVESI  # Tên cơ sở dữ liệu
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  # Đảm bảo MySQL hỗ trợ tiếng Việt
    networks:
      - hethong-chothuevesi-network
    volumes:
      - my_mysql_data:/var/lib/mysql  # Mount volume cho dữ liệu MySQL
      - ./init-db-scripts:/docker-entrypoint-initdb.d  # Mount thư mục chứa script vào container

networks:
  hethong-chothuevesi-network:
    driver: bridge

volumes:
  my_mysql_data:
