server:
  port: 8080
  servlet:
    context-path: /HuXu

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
    oauth2:
      client:
        registration:
          google:
            client-id: 1072233746069-nnpre089fhuiva9stirivseni2467ihv.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/auth/google/callback"
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  mail:
    host: smtp.gmail.com
    port: 587
    username: bodyguardhethongchothuevesi@gmail.com
    password: oubaztkfxmcjhjcb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    mail-from: bodyguardhethongchothuevesi@gmail.com
  application:
    serverLocal: "http://localhost:3000"
    serverName: "BODYGUARD Hệ thống cho thuê vệ sĩ"
  datasource:
    url: jdbc:mysql://localhost:3306/HETHONGCHOTHUEVESI  # URL kết nối MySQL
    #    url: jdbc:mysql://172.17.0.2/HETHONGCHOTHUEVESI  # URL kết nối MySQL
    username: root  # Tên người dùng MySQL
    password: root  # Mật khẩu người dùng MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver cho MySQL
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate tự động cập nhật schema
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Cấu hình chiến lược đặt tên
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Sử dụng MySQL dialect cho Hibernate
    show-sql: true  # Hiển thị các câu lệnh SQL trong console

jwt:
  signerKey: "QQSXWNtiP/T2aZiWnIlOgGCH+Wi2w20a6+ATaueWc5K3dybLoGMuNmAseN8oXGk6"  # Key dùng để ký JWT token
