server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HETHONGCHOTHUEVESI
    username: root
    password: root
    driver-class-name: com.mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: