server:
  port: 8080
  servlet:
    context-path: /HuXu
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HETHONGCHOTHUEVESI
    username: root
    password: root
#    driver-class-name: com.mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect:
    show-sql: true

