# This file contains sensitive keys and secrets. Do not commit this file to version control.

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "1019379455851-ql3lienhckt4aba3rrf91fi4219d4kas.apps.googleusercontent.com"
            client-secret: "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"
  mail:
    username: "bodyguardhethongchothuevesi@gmail.com"
    password: "oubaztkfxmcjhjcb"
  datasource:
    username: "root"
    password: "root"
vnpay:
  tmnCode: "94LW3UEC"
  hashSecret: "E9HHJMD5Z1LN50UPACXH45UVKRFAKQTT"
cloudinary:
  api-key: "216351684631253"
  api-secret: "fRGOb4gsJ63b6t9xM1bWHTYcpFg"
jwt:
  signerKey: "QQSXWNtiP/T2aZiWnIlOgGCH+Wi2w20a6+ATaueWc5K3dybLoGMuNmAseN8oXGk6"
